// ------------------------------------------------------------------------------------------------
// This code was generated by TeaForResource
// Created by Software Wizard
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression

namespace ResourceGenerator.Resources
{
    public static class ErrorKeys
    {
        public static string[] AllItems
        {
			get
			{
				return new []
				{
 		            "ElementNotFound",
                 };
            }
        }

		public static string ElementNotFound = "ElementNotFound";
    }
    public static class UiCaptionKeys
    {
        public static string[] AllItems
        {
			get
			{
				return new []
				{
 		            "Save",
 		            "Cancel",
 		            "Back",
 		            "Close",
 		            "About",
 		            "SaveAs",
                 };
            }
        }

		public static string Save = "Save";
		public static string Cancel = "Cancel";
		public static string Back = "Back";
		public static string Close = "Close";
		public static string About = "About";
		public static string SaveAs = "SaveAs";
    }
    public static class UiEnumKeys
    {
        public static string[] AllItems
        {
			get
			{
				return new []
				{
 		            "Admin",
 		            "Users",
                 };
            }
        }

		public static string Admin = "Admin";
		public static string Users = "Users";
    }

}
// </auto-generated>